Update install_arm-none-eabi-gcc.sh
Avoid broken builds due to:

  main.c:64:2: error: #error "newlib lacks support of long long type in IO functions. Please use a toolchain that was compiled with option --enable-newlib-io-long-long."